# Generated by Django 3.1.3 on 2020-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=300)),
                ('customer_type', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('place_id', models.CharField(max_length=200)),
                ('latitude_origin', models.FloatField(max_length=30)),
                ('longitude_origin', models.FloatField(max_length=30)),
                ('latitude_destination', models.FloatField(max_length=30)),
                ('longitude_destination', models.FloatField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('distance_driving', models.FloatField(max_length=100)),
            ],
        ),
    ]
